### ISSUE TITLE
compatibility to new sp/rgdal

### ISSUE THREAD

**Issue by aleruete** [Greensway/BIRDS#17]
In reverse dependency checks, there appear to be more problems with current **sp** from github - rsbivand/sp and R-Forge **rgdal**.  The underlying problem seems to stem from CRS(proj4string(x)), testing that proj4string() values are equal, and so on. Be aware that proj4string() values are retained only for out-of-date PROJ/GDAL versions, and that other mechanisms are used replacing the use of Proj4 strings with WKT2_2019 strings for PROJ >= 6 and GDAL >= 3 (already in the CRAN Windows binaries of sf and rgdal). You also use constructions like `points@proj4string` which should always be slot(points, "proj4string"). This is certainly not resolved. There are multiple errors when running soon to be released sp/rgdal with current PROJ/GDAL both on released BIRDS, and possibly more problems with BIRDS master.

_Originally posted by @rsbivand in https://github.com/Greensway/BIRDS/issues/9#issuecomment-687835782_

**Comment by rsbivand** [comment]
This is now urgent, as **sp** is being released and breaks **BIRDS**

**Comment by aleruete** [comment]
Hi Roger, 
I made a few changes on my package that are not yet released. Any suggestions for backwards compatibility?

**Comment by rsbivand** [comment]
Current master seens to complete CMD check with two NOTEs, with **sp** 1.4-4 and **rgdal** 1.5-17 and PROJ 7.1.1 and GDAL 3.1.3. This is better than released BIRDS: 2 ERRORs, 1 WARNING, 2 NOTEs. I do not know what you mean by "backwards compatibility"; if you need to support users with old scripts or old stored objects, you'll need to condition on **sp** and **rgdal** versions, and possibly on PROJ/GDAL versions. No packages depend on or import from BIRDS, so I'm unsure whether there are any reasons to do anything other than alert users to any user-visible changes to the only published version of your package.
