### ISSUE TITLE
rename? Visits --> checklists

### ISSUE THREAD

**Issue by aleruete** [Greensway/BIRDS#5]
should be rename visits everywhere to call them checklists (chklst)? Comment please

**Comment by DeboraArlt** [comment]
No, I would not. The term checklist is slightly confusing. Seems like many start understanding and using it as the list of species somone observed. But I think originally it's like a list of species possible to be found in an area, e.g. checklist of bird of Sweden (would be all potential species that one could encounter, and then check when seen). Artportalens checklist is a lists of species that can occur at a given place and time but not the list of species actually seen - so the potential list can be (as it is in this case) specific to a visit. But the checklist as such is not the same as a visit. I think 'checklist' is sometimes used a bit sloppy to mean the actual list of species seen during a visit. 

What term do people use in papers when they refer to a set of records from the same person at same location and time,?

**Comment by aleruete** [comment]
ok, then I write in the readme when we define Visits that it may be called Chesklist, but do not mix with... bla bla..
