### ISSUE TITLE
zoo:index(x)

### ISSUE THREAD

**Issue by aleruete** [Greensway/BIRDS#7]
**Describe the bug**
Sometimes when reloading summarise birds it trows the following error when I run focalSpReport:

`Error in as.POSIXlt.numeric(zoo::index(x)) : 'origin' must be supplied`

It doens't happens always.

**To Reproduce**
Likely `yearsAll <- sort(unique(lubridate::year(x$temporal)))`

Reported by Charles

**Comment by SphagnumPI** [comment]
This can be fixed by renewing summarise birds (SB) temporal data frame to as.zoo object.

**Comment by SphagnumPI** [comment]
I have fixed this now. I save by saving  time(SB$temporal) to SBTimes  I then recreate the zoo object by checking if there is and error and then reattaching the times to the SB$temporal
err=try(focalSpSummary(SB,spList[1])) 
 if(grepl("origin' must be supplied",err)){
   times=readRDS(list.files(dirs[j],pattern="Temporal",full.names = TRUE))
   SB$temporal=zoo(SB$temporal,times)
 }

**Comment by Greensway** [comment]
Actually, the index is (sometimes?) saved as POSIXlt. You can fix this by 
if they dont have date format
`if (all(is.na(as.Date(as.character(index(SB$temporal)), format="%Y-%m-%d")))){         
         times <- as.POSIXlt(index(SB$temporal), 
                             tz = attr(index(SB$temporal),"tzone"), 
                             origin = "1970-01-01 00:00.00 UTC")
         SB$temporal<-zoo(SB$temporal, times)
      }`
